---
- name: Install vim.
  yum: name=vim state=present

- name: Install JQ
  yum: name=jq-1.5-1.el7.x86_64 state=present

- name: Install locate.
  yum: name=mlocate state=present
  register: result

- name: Update db
  command: updatedb
  when: result|succeeded


