---
- name: Install common utils.
  yum: state=present name="{{ item }}"
  with_items:
    - vim
    - jq-1.5-1.el7.x86_64
    - mlocate
    - mod_ssl
  register: result

- name: Update db
  command: updatedb
  when: result|succeeded


